[package]
name = "snake"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
tokio = { version = "1.47.1", features = ["full"] }
tokio-stream = "0.1"
reqwest = { version = "0.12", features = ["json"] }
hyper = "1.7.0"
dotenvy = "0.15.7"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
bytes = "1.10.1"
http-body-util = "0.1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
self_update = { version = "0.41", features = [
  "archive-tar",
  "compression-flate2",
] }
semver = "1.0"
